//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int Id { get; set; }
        public Nullable<int> Movie { get; set; }
        public string Description { get; set; }
        public string Genre { get; set; }
        public string Film_rating { get; set; }
        public string Main_character { get; set; }
        public string Running_time { get; set; }
        public Nullable<int> is3D { get; set; }
        public Nullable<int> World_score { get; set; }
    
        public virtual Movy Movy { get; set; }
    }
}
