//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int Id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public string FIO { get; set; }
        public string company { get; set; }
        public string phone { get; set; }
        public string acountant { get; set; }
        public string address { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
    }
}
