//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string amount { get; set; }
        public Nullable<double> sum { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Products Products { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
