//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public int Id { get; set; }
        public string lastname { get; set; }
        public Nullable<int> group { get; set; }
        public Nullable<System.DateTime> admission_year { get; set; }
        public Nullable<byte> rating { get; set; }
    
        public virtual groups groups { get; set; }
    }
}
